import { GLOBE_LAND } from "@/components/hero/globe-paths";

/**
 * The planet the episodes go round.
 *
 * Purely decorative — aria-hidden, no text, no focus stop. The episode cards
 * carry all the meaning in the hero; this is the thing they orbit.
 *
 * Drawn, not textured. There is no globe bitmap in the repo, and a photographic
 * earth would drag in colours the brand does not have. The surface is four flat
 * layers, bottom to top:
 *
 *   ocean   radial gradient, lit from the north       (.mm-globe background)
 *   land    the continents, near-black                (.mm-globe-land)
 *   shade   limb darkening + terminator + scanlines   (.mm-globe-shade)
 *   limb    the atmosphere rim                        (.mm-globe-limb)
 *
 * Land sits *under* the shading so one terminator falls across sea and continent
 * alike. Shade the land separately and it reads as a sticker on a ball.
 *
 * The sphere stays inside the orbit radius so the cards ride clear of its surface
 * rather than clipping through it — it is the thing they go round, so it has to
 * be smaller than the belt.
 *
 * The coastlines are real: Natural Earth 50m through an orthographic projection,
 * generated by scripts/generate-globe.mjs into globe-paths.ts. To move the camera,
 * change CENTRE in the generator and re-run `npm run globe` — do not edit the
 * path data, and do not hand-draw over it.
 */
export function Globe() {
  return (
    <>
      <div className="mm-globe" aria-hidden="true">
        <svg
          className="mm-globe-land"
          viewBox="0 0 1000 1000"
          xmlns="http://www.w3.org/2000/svg"
          aria-hidden="true"
          focusable="false"
        >
          <path className="mm-globe-land-path" d={GLOBE_LAND} />
        </svg>
        <span className="mm-globe-shade" />
        <span className="mm-globe-limb" />
      </div>
      {/* The stage crops the globe's bloom mid-falloff. Without this the cut is a
          hard horizontal seam across the page. */}
      <div className="mm-globe-horizon" aria-hidden="true" />
    </>
  );
}
