/**
 * Generates the hero globe's coastlines from Natural Earth data.
 *
 *   node scripts/generate-globe.mjs      (or: npm run globe)
 *
 * Writes components/hero/globe-paths.ts. That file is GENERATED — never hand-edit
 * it, the same rule styles/tokens.css lives under. Nudging one projected path by
 * hand desyncs it from every other shape on the sphere.
 *
 * Why generate rather than draw: hand-drawn continents at this size read as
 * spilled ink. Real Natural Earth outlines through a real orthographic projection
 * read as Earth, which is the entire job of the element.
 *
 * d3-geo does the projection AND the hard part — clipping each ring against the
 * visible hemisphere and closing it along the limb, so nothing short-circuits
 * across the disc. Everything on the far side is simply absent, which is correct.
 *
 * The dependencies are devDependencies and the output is committed, so none of
 * this ships: the site serves a string of path data and no geo library at all.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoOrthographic, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);

/** Camera. Atlantic view: Americas facing us, Africa and Europe on the right limb. */
const CENTRE = { lon: -55, lat: 18 };
/** Disc geometry, matching the 0 0 1000 1000 viewBox in Globe.tsx. */
const R = 500;
/**
 * 50m is the sweet spot. 110m loses Florida, the Gulf and the Great Lakes — the
 * silhouettes that make it legible as Earth. 10m triples the byte count for
 * detail that dies at 600px.
 */
const SOURCE = "world-atlas/land-50m.json";
/**
 * Screen px below which a landmass is a speck. Drops a few thousand islands that
 * survive the projection as single-pixel dots but cost real bytes.
 */
const MIN_AREA = 4;

const projection = geoOrthographic()
  .rotate([-CENTRE.lon, -CENTRE.lat])
  .scale(R)
  .translate([R, R])
  .clipAngle(90);

/**
 * geoPath streams to a canvas-like context, so simplification happens here in
 * screen space rather than on the geometry: round to whole viewBox units, and
 * drop any vertex within MIN_STEP of the one before it.
 *
 * The disc is 1000 units wide and paints at ~600px, so a unit is 0.6px and the
 * raw 50m coastline spends most of its 336kB describing detail below half a
 * pixel. Filtering here keeps every silhouette that survives at this size and
 * throws away only what the rasteriser was going to collapse anyway.
 *
 * Doing it in the stream also avoids post-processing the path string, which is
 * a good way to corrupt an arc flag.
 */
const MIN_STEP = 2;

function simplifyingContext() {
  const r = Math.round;
  let out = [];
  let last = null;
  let count = 0;
  let start = 0;
  return {
    moveTo(x, y) {
      last = [r(x), r(y)];
      count = 1;
      start = out.length;
      out.push(`M${last[0]} ${last[1]}`);
    },
    lineTo(x, y) {
      const px = r(x);
      const py = r(y);
      if (last && Math.hypot(px - last[0], py - last[1]) < MIN_STEP) return;
      last = [px, py];
      count++;
      out.push(`L${px} ${py}`);
    },
    arc() {},
    closePath() {
      // A ring reduced below a triangle encloses nothing; drop the whole subpath
      // rather than emit a degenerate one.
      if (count < 3) out.length = start;
      else out.push("Z");
      last = null;
      count = 0;
    },
    take() {
      const s = out.join("");
      out = [];
      last = null;
      count = 0;
      return s;
    },
  };
}

const ctx = simplifyingContext();
const path = geoPath(projection, ctx);
const area = geoPath(projection);

const topo = require(SOURCE);
// topojson's `feature` hands back a FeatureCollection for a GeometryCollection
// source, which is what land-50m is.
const land = feature(topo, topo.objects.land);
const geometry =
  land.type === "FeatureCollection" ? land.features[0].geometry : land.geometry;

// Split the land MultiPolygon so each landmass can be measured on its own; a
// single feature would only ever report one combined area.
const polygons = geometry.coordinates.map((coordinates) => ({
  type: "Polygon",
  coordinates,
}));

let kept = 0;
let dropped = 0;
const pieces = [];
for (const polygon of polygons) {
  if (area.area(polygon) < MIN_AREA) {
    dropped++;
    continue;
  }
  path(polygon);
  const d = ctx.take();
  if (d) {
    pieces.push(d);
    kept++;
  }
}

const file = `// GENERATED by scripts/generate-globe.mjs — do not edit by hand.
// Natural Earth land (50m) in an orthographic projection centred on
// ${Math.abs(CENTRE.lon)}°${CENTRE.lon < 0 ? "W" : "E"} ${Math.abs(CENTRE.lat)}°${CENTRE.lat < 0 ? "S" : "N"},
// clipped to the visible hemisphere. Disc radius ${R} in a 0 0 1000 1000 viewBox.
// Re-run the generator to move the camera.

/** Every landmass above the size cutoff, as one fill. */
export const GLOBE_LAND = ${JSON.stringify(pieces.join(""))};
`;

const out = new URL("../components/hero/globe-paths.ts", import.meta.url);
writeFileSync(out, file);

const kb = (s) => `${(s.length / 1024).toFixed(1)}kB`;
console.log(
  `land:      ${kept} shapes, ${dropped} specks dropped, ${kb(pieces.join(""))}`,
);

console.log("wrote      components/hero/globe-paths.ts");
