#!/usr/bin/env node
/**
 * design/figma-tokens.json  ->  styles/tokens.css
 *
 * The Figma variables already carry their CSS custom-property name in their WEB
 * code syntax, so this is a mechanical transform, not a mapping anyone maintains
 * by hand. Refresh figma-tokens.json from the Figma MCP, then run `npm run tokens`.
 *
 * Emits plain custom properties plus a Tailwind v4 @theme block, so tokens are
 * usable both as var(--mm-*) and as utility classes.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = resolve(root, "design/figma-tokens.json");
const out = resolve(root, "styles/tokens.css");

const t = JSON.parse(readFileSync(src, "utf8"));

const px = (v) => `${v}px`;
const lines = [];

lines.push("/* GENERATED by scripts/generate-tokens.mjs from design/figma-tokens.json.");
lines.push(
  " * Do not edit. Change the Figma variable, refresh the JSON, run `npm run tokens`.",
);
lines.push(` * Source: Figma qUhg8iR0L0TAOqv3QQ7pAM, generated ${t._generated}. */`);
lines.push("");
lines.push(":root {");

const section = (title, entries, fmt) => {
  lines.push(`  /* ${title} */`);
  for (const e of entries) lines.push(`  ${e.css}: ${fmt(e)};`);
  lines.push("");
};

section("colour", t.colors, (e) => e.value);
section("spacing", t.space, (e) => px(e.value));
section("radius", t.radius, (e) => (e.value >= 999 ? "9999px" : px(e.value)));
section("sizing", t.size, (e) => px(e.value));
section("type families", t.fonts, (e) =>
  e.css === "--mm-font-mono"
    ? `"${e.value}", ui-monospace, SFMono-Regular, monospace`
    : `"${e.value}", ui-sans-serif, system-ui, sans-serif`,
);

lines.push("}");
lines.push("");

// Tailwind v4 consumes CSS vars directly, so every token becomes a utility.
lines.push("@theme inline {");
for (const c of t.colors) {
  lines.push(`  --color-${c.css.replace(/^--mm-/, "mm-")}: var(${c.css});`);
}
lines.push("  --font-display: var(--mm-font-display);");
lines.push("  --font-mono: var(--mm-font-mono);");
lines.push("}");
lines.push("");

// Type ramp as composable utility classes; keeps font-size/leading/tracking together
// so a heading can never drift from its Figma style.
lines.push("@layer components {");
for (const s of t.textStyles) {
  lines.push(`  .type-${s.name} {`);
  lines.push(`    font-family: var(--mm-font-${s.family});`);
  lines.push(`    font-weight: ${s.weight};`);
  lines.push(`    font-size: ${px(s.size)};`);
  lines.push(`    line-height: ${s.lineHeight};`);
  lines.push(`    letter-spacing: ${s.tracking}em;`);
  if (s.case) lines.push(`    text-transform: ${s.case};`);
  lines.push("  }");
}
lines.push("}");
lines.push("");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n"), "utf8");

const count =
  t.colors.length + t.space.length + t.radius.length + t.size.length + t.fonts.length;
console.log(
  `tokens: ${count} custom properties + ${t.textStyles.length} type styles -> styles/tokens.css`,
);
