/**
 * Downscales the photo masters in Assets/ into the copies the site serves.
 *
 *   npm run photos
 *
 * Everything in public/brand/*.jpg is GENERATED by this. Edit the master or this
 * script, never the output.
 *
 * WHY THIS EXISTS. The three photographs were camera originals copied verbatim
 * into public/brand/ — byte-identical to their masters, 1.3 to 2.5 MB each, six
 * megabytes of the same pixels twice. next/image meant visitors never downloaded
 * that, but every clone carried it, and the first request for a cold panel paid a
 * 2.5 MB transform to produce a 1056 px picture.
 *
 * Sizes below are twice the largest CSS width each image is ever rendered at,
 * which is what a 2x display needs and the point past which next/image is
 * throwing pixels away regardless.
 *
 * Rasterising happens in Chromium rather than a pure-JS encoder, for the same
 * reason scripts/generate-favicon.mjs does it: Playwright is already a
 * devDependency, and the browser's downscale filter is better than anything worth
 * hand-rolling.
 *
 * The masters stay tracked so this runs from a fresh clone. Re-run it after
 * replacing one, and commit both the master and the output.
 */
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { chromium } from "@playwright/test";

/**
 * `crop` takes a rectangle out of the master before downscaling, in MASTER
 * PIXELS. It exists because the two host photographs are not the same kind of
 * picture: Ben's master is already a square head-and-shoulders, and Keith's is a
 * full-length portrait where the face occupies about a fifth of the frame.
 *
 * Dropping the second into the same card left him small and low in it while Ben
 * filled his, and no amount of `object-position` fixes that — `object-fit: cover`
 * can only slide the window over the image, never tighten it. The zoom has to
 * happen to the pixels, which is here.
 *
 * The numbers are tied to the specific master named above. Replace that file and
 * they mean nothing, so re-derive them: they are a square, centred on the face,
 * sized so the head fills about two thirds of it — which is what Ben's does.
 */
const JOBS = [
  {
    // The info panel cover. Panel caps at 1120px less 64px of padding.
    from: "../Assets/keith-ben-cover.jpg",
    to: "../public/brand/keith-ben-cover.jpg",
    width: 2112,
  },
  {
    // Host cards: 580px on About, 220px in the panel.
    from: "../Assets/Kieth_D_profile_pic.JPG",
    to: "../public/brand/keith-d.jpg",
    width: 1160,
    // Master is 2246x3387.
    crop: { x: 636, y: 841, w: 1012, h: 1012 },
  },
  {
    // No crop: this master is already framed the way the card wants it.
    from: "../Assets/Ben_profile_pic.jpg",
    to: "../public/brand/ben-leavitt.jpg",
    width: 1160,
  },
];

/** High enough that the artefacts are invisible at these sizes, low enough to matter. */
const QUALITY = 0.82;

const kb = (bytes) => `${Math.round(bytes / 1024)} kB`;

const browser = await chromium.launch();
const page = await browser.newPage();

let missing = 0;

for (const job of JOBS) {
  const source = new URL(job.from, import.meta.url);
  const target = new URL(job.to, import.meta.url);

  if (!existsSync(source)) {
    console.warn(`skipped ${job.from} — master not present`);
    missing++;
    continue;
  }

  const before = statSync(source).size;
  const dataUri = `data:image/jpeg;base64,${readFileSync(source).toString("base64")}`;

  const encoded = await page.evaluate(
    async ({ dataUri, width, quality, crop }) => {
      const img = new Image();
      img.src = dataUri;
      await img.decode();

      // The source rectangle: the whole master unless a crop asked otherwise.
      // Clamped to the image so a stale rectangle produces a wrong-looking
      // picture rather than a silently blank one.
      const sx = crop ? Math.max(0, Math.min(crop.x, img.naturalWidth - 1)) : 0;
      const sy = crop ? Math.max(0, Math.min(crop.y, img.naturalHeight - 1)) : 0;
      const sw = crop ? Math.min(crop.w, img.naturalWidth - sx) : img.naturalWidth;
      const sh = crop ? Math.min(crop.h, img.naturalHeight - sy) : img.naturalHeight;

      // Never upscale: a source smaller than the target is served as it is.
      const scale = Math.min(1, width / sw);
      const canvas = document.createElement("canvas");
      canvas.width = Math.round(sw * scale);
      canvas.height = Math.round(sh * scale);

      const ctx = canvas.getContext("2d");
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = "high";
      ctx.drawImage(img, sx, sy, sw, sh, 0, 0, canvas.width, canvas.height);

      return {
        uri: canvas.toDataURL("image/jpeg", quality),
        w: canvas.width,
        h: canvas.height,
        source: `${img.naturalWidth}x${img.naturalHeight}`,
      };
    },
    { dataUri, width: job.width, quality: QUALITY, crop: job.crop ?? null },
  );

  const bytes = Buffer.from(encoded.uri.split(",")[1], "base64");
  writeFileSync(target, bytes);

  const saved = Math.round((1 - bytes.length / before) * 100);
  console.log(
    `${job.to.replace("../", "")}  ${encoded.source}${job.crop ? " cropped" : ""} -> ${encoded.w}x${encoded.h}  ${kb(before)} -> ${kb(bytes.length)}  (-${saved}%)`,
  );
}

await browser.close();

if (missing === JOBS.length) {
  console.error("\nNo masters found. They are not carried in the repo — see .gitignore.");
  process.exitCode = 1;
}
