/**
 * Downscales the photo masters in Assets/ into the copies the site serves.
 *
 *   npm run photos
 *
 * Everything in public/brand/*.jpg is GENERATED by this. Edit the master or this
 * script, never the output.
 *
 * WHY THIS EXISTS. The three photographs were camera originals copied verbatim
 * into public/brand/ — byte-identical to their masters, 1.3 to 2.5 MB each, six
 * megabytes of the same pixels twice. next/image meant visitors never downloaded
 * that, but every clone carried it, and the first request for a cold panel paid a
 * 2.5 MB transform to produce a 1056 px picture.
 *
 * Sizes below are twice the largest CSS width each image is ever rendered at,
 * which is what a 2x display needs and the point past which next/image is
 * throwing pixels away regardless.
 *
 * Rasterising happens in Chromium rather than a pure-JS encoder, for the same
 * reason scripts/generate-favicon.mjs does it: Playwright is already a
 * devDependency, and the browser's downscale filter is better than anything worth
 * hand-rolling.
 *
 * The masters stay tracked so this runs from a fresh clone. Re-run it after
 * replacing one, and commit both the master and the output.
 */
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { chromium } from "@playwright/test";

const JOBS = [
  {
    // The info panel cover. Panel caps at 1120px less 64px of padding.
    from: "../Assets/keith-ben-cover.jpg",
    to: "../public/brand/keith-ben-cover.jpg",
    width: 2112,
  },
  {
    // Host cards: 580px on About, 220px in the panel.
    from: "../Assets/Kieth_D_profile_pic.JPG",
    to: "../public/brand/keith-d.jpg",
    width: 1160,
  },
  {
    from: "../Assets/Ben_profile_pic.jpg",
    to: "../public/brand/ben-leavitt.jpg",
    width: 1160,
  },
];

/** High enough that the artefacts are invisible at these sizes, low enough to matter. */
const QUALITY = 0.82;

const kb = (bytes) => `${Math.round(bytes / 1024)} kB`;

const browser = await chromium.launch();
const page = await browser.newPage();

let missing = 0;

for (const job of JOBS) {
  const source = new URL(job.from, import.meta.url);
  const target = new URL(job.to, import.meta.url);

  if (!existsSync(source)) {
    console.warn(`skipped ${job.from} — master not present`);
    missing++;
    continue;
  }

  const before = statSync(source).size;
  const dataUri = `data:image/jpeg;base64,${readFileSync(source).toString("base64")}`;

  const encoded = await page.evaluate(
    async ({ dataUri, width, quality }) => {
      const img = new Image();
      img.src = dataUri;
      await img.decode();

      // Never upscale: a master smaller than the target is served as it is.
      const scale = Math.min(1, width / img.naturalWidth);
      const canvas = document.createElement("canvas");
      canvas.width = Math.round(img.naturalWidth * scale);
      canvas.height = Math.round(img.naturalHeight * scale);

      const ctx = canvas.getContext("2d");
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = "high";
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

      return {
        uri: canvas.toDataURL("image/jpeg", quality),
        w: canvas.width,
        h: canvas.height,
      };
    },
    { dataUri, width: job.width, quality: QUALITY },
  );

  const bytes = Buffer.from(encoded.uri.split(",")[1], "base64");
  writeFileSync(target, bytes);

  const saved = Math.round((1 - bytes.length / before) * 100);
  console.log(
    `${job.to.replace("../", "")}  ${encoded.w}x${encoded.h}  ${kb(before)} -> ${kb(bytes.length)}  (-${saved}%)`,
  );
}

await browser.close();

if (missing === JOBS.length) {
  console.error("\nNo masters found. They are not carried in the repo — see .gitignore.");
  process.exitCode = 1;
}
