/**
 * Refreshes the committed channel-stats fallback.
 *
 *   YOUTUBE_API_KEY=... node scripts/refresh-stats.mjs           (npm run stats:refresh)
 *   YOUTUBE_API_KEY=... node scripts/refresh-stats.mjs --check    verify only, never write
 *
 * content/channel-stats-fallback.json is what the social-proof band renders
 * whenever the live API is unreachable — or whenever no key is configured at
 * all, which is the state a fresh clone is in. So it is not a disaster-recovery
 * file that never runs; on a site without the key it is the ONLY source, and
 * every week nobody refreshes it the numbers on the page drift further below the
 * truth.
 *
 * Understating the audience is the safe direction — better than a page claiming
 * subscribers the channel does not have — but it is still wrong, and it is wrong
 * on the figures a sponsor reads.
 *
 * Imports lib/stats.ts rather than parsing the response here, for the same
 * reason refresh-episodes.mjs imports lib/feed.ts: a script with its own parser
 * proves some parser can read the API, which is not the question. Node strips
 * the TypeScript natively (>= 22.6).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { CHANNEL_ID } from "../lib/feed.ts";
import { parseStats } from "../lib/stats.ts";

const OUT = new URL("../content/channel-stats-fallback.json", import.meta.url);
const checkOnly = process.argv.includes("--check");
const KEY = process.env.YOUTUBE_API_KEY;

if (!KEY) {
  console.error("YOUTUBE_API_KEY is not set.");
  console.error("Create one at console.cloud.google.com — enable YouTube Data API v3,");
  console.error(
    "Credentials -> Create credentials -> API key. It is free and read-only.",
  );
  process.exitCode = 1;
}

if (KEY) {
  const url = `https://www.googleapis.com/youtube/v3/channels?part=statistics&id=${CHANNEL_ID}&key=${KEY}`;

  let res;
  try {
    res = await fetch(url);
  } catch (err) {
    console.error(`could not reach the YouTube API: ${err.message}`);
    process.exitCode = 1;
  }

  if (res) {
    if (!res.ok) {
      // 403 is nearly always the key: either the API is not enabled on the
      // project, or a referrer/IP restriction excludes wherever this is running.
      console.error(`the API returned HTTP ${res.status}`);
      console.error(await res.text());
      process.exitCode = 1;
    } else {
      const stats = parseStats(await res.json());
      if (!stats) {
        console.error("the API answered but the body had no usable statistics.");
        console.error("Check the channel id, and whether the count is hidden.");
        process.exitCode = 1;
      } else {
        const current = JSON.parse(readFileSync(OUT, "utf8"));
        const next = {
          _comment:
            "GENERATED by scripts/refresh-stats.mjs. Cold-start fallback for lib/stats.ts, " +
            "used when the YouTube Data API is unreachable or YOUTUBE_API_KEY is unset. " +
            "Re-run the script rather than editing by hand.",
          capturedAt: stats.capturedAt,
          subscribers: stats.subscribers,
          views: stats.views,
          videos: stats.videos,
        };

        const delta = (key) => {
          const from = current[key];
          const to = next[key];
          const sign = to >= from ? "+" : "";
          return `${key}: ${from.toLocaleString("en-GB")} -> ${to.toLocaleString("en-GB")} (${sign}${(to - from).toLocaleString("en-GB")})`;
        };
        console.log(`live: ${delta("subscribers")}`);
        console.log(`      ${delta("views")}`);
        console.log(`      ${delta("videos")}`);

        const setOutput = (changed) => {
          if (process.env.GITHUB_OUTPUT) {
            writeFileSync(process.env.GITHUB_OUTPUT, `stats_changed=${changed}\n`, {
              flag: "a",
            });
          }
        };

        const same = ["subscribers", "views", "videos"].every(
          (k) => current[k] === next[k],
        );
        if (same) {
          console.log("\nfallback already current, nothing to write");
          setOutput(false);
        } else if (checkOnly) {
          console.log("\n--check: not writing. Run without the flag to update.");
          setOutput(false);
        } else {
          writeFileSync(OUT, `${JSON.stringify(next, null, 2)}\n`);
          console.log(`\nwrote content/channel-stats-fallback.json (${next.capturedAt})`);
          setOutput(true);
        }
      }
    }
  }
}
